import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import RecorderControls from '@/components/recorder-controls';
import { UseRecorder } from '@/types/recorder';
import useRecorder from '@/hooks/use-recorder';
import RecordingsList from '@/components/recordings-list';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const { recorderState, ...handlers }: UseRecorder = useRecorder();
	const { audio } = recorderState;
	// const [recorder, setRecorder] = useState<any>(null);
	// const [recordedAudio, setRecordedAudio] = useState(null);
	// const [isRecording, setIsRecording] = useState(false);

	// const handleRecordClick = async () => {
	// 	const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
	// 	const mediaRecorder = new MediaRecorder(stream);
	// 	const audioChunks: any = [];

	// 	mediaRecorder.addEventListener('dataavailable', event => {
	// 		audioChunks.push(event.data);
	// 	});

	// 	mediaRecorder.addEventListener('stop', () => {
	// 		const audioBlob = new Blob(audioChunks);
	// 		const audioUrl = URL.createObjectURL(audioBlob);
	// 		setRecordedAudio(audioUrl as any);
	// 	});

	// 	mediaRecorder.start();
	// 	setIsRecording(true);
	// 	setRecorder(mediaRecorder);
	// };

	// const handleStopClick = () => {
	// 	recorder.stop();
	// 	setIsRecording(false);
	// };

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<div className="bg-gray-100 h-[100vh] px-[20%]">
				<div className=" flex flex-col items-start justify-center">
					<div>
						<span>What is your goal?</span>
					</div>
					<div className=" flex flex-col items-start">
						<div className=" text-xl">
							<RecorderControls
								recorderState={recorderState}
								handlers={handlers}
							/>
						</div>
						<div className=" text-start">
							<span>My goal is..</span>
						</div>
						<RecordingsList audio={audio} />
					</div>
				</div>
			</div>
		</>
	);
}
